### ISSUE TITLE
#Album with AddURIToQueue  does not work

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#108]
With node-sonos-ts I am not able to add the following URI to SONOS queue neither with valid metadata nor without. I tried: "AddUriToQueue" but also from "AVTransportService" and with direct execute. 

```
{
    "InstanceID": 0,
    "EnqueuedURI": "x-rincon-playlist:RINCON_000E58FE3AEA01400#A:ALBUM/Diamond%20Life",
    "EnqueuedURIMetaData": "",
    "DesiredFirstTrackNumberEnqueued": 0,
    "EnqueueAsNext": 1
}
```

It works fine in node-sonos. 

Looking at the generated SOAP request there is a small difference - two times  "\r\n" or do you see any other differences?

SOAP body generated in nodes-sonos-ts causing an error message: 
`"<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\r\n<s:Body><u:AddURIToQueue xmlns:u=\"urn:schemas-upnp-org:service:AVTransport:1\"><InstanceID>0</InstanceID><EnqueuedURI>x-rincon-playlist:RINCON_000E58FE3AEA01400#A%3aALBUM/Diamond%20Life</EnqueuedURI><EnqueuedURIMetaData></EnqueuedURIMetaData><DesiredFirstTrackNumberEnqueued>0</DesiredFirstTrackNumberEnqueued><EnqueueAsNext>1</EnqueueAsNext></u:AddURIToQueue></s:Body>\r\n</s:Envelope>"
`

versus the one which works:
`"<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><s:Body><u:AddURIToQueue xmlns:u=\"urn:schemas-upnp-org:service:AVTransport:1\"><InstanceID>0</InstanceID><EnqueuedURI>x-rincon-playlist:RINCON_000E58FE3AEA01400#A:ALBUM/Diamond%20Life</EnqueuedURI><EnqueuedURIMetaData></EnqueuedURIMetaData><DesiredFirstTrackNumberEnqueued>0</DesiredFirstTrackNumberEnqueued><EnqueueAsNext>1</EnqueueAsNext></u:AddURIToQueue></s:Body></s:Envelope>"`

**Comment by svrooij** [comment]
`3AEA01400#A%3aALB`
