### ISSUE TITLE
BUG: VirtualLineInService - not receiving any events

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#121]
### What happened

After subscribing to VirtualLineInService I don't receive any events. The server shows the subscription. 

Maybe you already recognized, that I am testing all Service. All work fine - except this one.

It  has low priority. Currently I have no use case - just to explore the features.

### What did you expect to happen

Receive at least the initial events. 

### Debug logging
sonos:eventlistener does provide information about the other Service I subscribed but not for VirtualLineIn

### Environment

- sonos-ts version: 2.3.4
- OS: Windows 10

### Checklist

Please confirm the following before creating the issue.

**Comment by svrooij** [comment]
It says in the documentation that it has events, but I could not get them to work either. Closing this issue for now.

**Comment by hklages** [comment]
maybe then it should be removed from the documentation: 
[virtuallineIn](https://svrooij.io/node-sonos-ts/sonos-device/services/virtual-line-in-service.html#virtuallineinservice-event)

**Comment by svrooij** [comment]
The documentation is generated from the service discovery. So if it says there is that service and it emits events then we keep it.

But a message that we could not get the events tested would be nice. I think that during the time I've added all the tests this was the only service where I can not generate the events and add them to the tests file.
