### ISSUE TITLE
BUG: RadioFavoritesUpdateID is NaN

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#122]
### What happened

Subscribing to ContentDirectoryService provides two properties with NaN : 

- RadioLocationUpdateID
- RadioFavoritesUpdateID

LOW PRIORITY - just to explore the capabilities.

### What did you expect to happen

maybe string - dont know as I have no access to the raw data from SONOS player

### How to reproduce it (minimal and precise)

just subscribe to that servce

### Debug logging
no raw data with sonos:eventlistener

### Environment

- sonos-ts version: 2.3.0
- OS: Windows
- node version (`node -v`):

**Comment by svrooij** [comment]
Not all events emit all properties. All event properties are defined as optional in the typescript code.

This is also stated in the documentation

https://svrooij.io/node-sonos-ts/sonos-device/services/content-directory-service.html#contentdirectoryservice-event
