### ISSUE TITLE
BUG: UUID and service name not displaced

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#126]
### What happened
uuid and service name are not displayed (see yellow part in screen shot)

### What did you expect to happen

The data and not the template literals

### How to reproduce it (minimal and precise)
Just subscribe to any event.

### Debug logging
![subscription](https://user-images.githubusercontent.com/17273119/105818248-f855ef00-5fb6-11eb-9095-a9601c0bf904.png)

`
sonos:eventlistener Listener endpoint: http://192.168.178.28:6329/sonos/{sonos-uuid}/{serviceName} +0ms | stdout

`

**Comment by svrooij** [comment]
This is by design, starting the EventListener isn't tied to a specific subscription. Because of this I deliberately added the `{` and `}` around it, **in the logging**. Hoping a developer seeing the logs would see it as template strings.
