### ISSUE TITLE
GroupID in ZoneGroupEvent missing

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#132]
## Is your feature request related to a problem? Please describe
No 

## Describe the solution you'd like
Get GroupID in ZoneGroup event and what would even better get the raw data in any Service event. Then I can parse/tranform as I need it. 

## Describe alternatives you've considered
- 

## Additional context
Low priority - GroupID is useful to sort players by group.

**Comment by svrooij** [comment]
The `Unprocessed` event on each service should do just that. That way you can parse the data if you think this library does it incorrectly.

https://github.com/svrooij/node-sonos-ts/blob/08198914ab7b09eec2350c59a3bf08cd8e207c03/src/services/base-service.ts#L502-L522

**Comment by svrooij** [comment]
You're probably looking for something like this:

```js
const XmlHelper = require('../lib/helpers/xml-helper').default;
const SonosDevice = require('../lib/').SonosDevice
const ServiceEvents = require('../lib/models/service-event').ServiceEvents;
const device = new SonosDevice('192.168.x.x');
device.ZoneGroupTopologyService.Events.on(ServiceEvents.Unprocessed, data => {
  //console.log('ZoneGroupTopology data %s', JSON.stringify(data))
  console.log('ZoneGroupState from event', JSON.stringify(XmlHelper.DecodeAndParseXml(data[0].ZoneGroupState, ''), null, 2))
})
```
