### ISSUE TITLE
debug 3.2.0 with low severity ReDos

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#134]
### What happened

npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4<4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1.

### What did you expect to happen

Please upgrade debug to latest.

**Comment by svrooij** [comment]
I updated some packages in the beta branch, but since this isn’t any functional change it won’t be released until some feature change.

**Comment by hklages** [comment]
Thanks for the rapid response. 
Its ok. We found a work around to install manually. 

The issues seems to be that iobroker automatically updates packages but only if there are no npm warnungs. 
So the update is kind of blocked there. Fortunately there is an option to do that manually in the Node-RED palette.
