### ISSUE TITLE
Line In, Audio Delay

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#139]
## Is your feature request related to a problem? Please describe

Request from a user, who needs that option - he captured traffice but that part seems to be encrypted.

## Describe the solution you'd like

In the Android app for line in there is the option Audio delay. You can choose low (75ms) to Max (2000ms).
Do you have any idee how to do that via sonos api?  

![Screenshot_20210720-201204_Sonos](https://user-images.githubusercontent.com/17273119/126374505-ad9f7f79-0731-474a-8411-0075a7756ab1.jpg)

**Comment by svrooij** [comment]
Sadly this cannot be done, there is no public API for this. See https://github.com/hklages/node-red-contrib-sonos-plus/issues/159#issuecomment-884781183

**@Sonos** if you're listening, please open your local rest api that is running (port `1433`) on devices we bought!
