### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#144]
### What happened

node-red crashes, io broker crashes and had to be restarted.

### How to reproduce it (minimal and precise)

Not available

### Debug logging

![error](https://user-images.githubusercontent.com/17273119/133495240-48647da1-5dc9-49cd-a4fd-85fe099ec6c0.png)

### Environment
- sonos-ts version: 2.4.0
- node version (`node -v`): current

**Comment by svrooij** [comment]
I’m not sure what to say, it seems like you’re not catching an error?

but without any information about what you did, or what commands you tried to execute I cannot find out what to do/change.
It says there is a network timeout, are you sure the speaker you’re trying to control was available when this happened?

Just curious, do you think this library should keep throwing errors or just silently ignore them? Is that the responsibility of this library or of the app using this library?

**Comment by hklages** [comment]
I use a async wrapper function and call all typescript-sonos procedures with await. 
In case of a time out I usually get the full stack showing your routine and my routine name. 

In this case the stack only shows the fetch routine so I thought that the unhandled execption is in your code.
I am going to ask the user for more information. 

> Just curious, do you think this library should keep throwing errors or just silently ignore them? Is that the responsibility of this library or of the app using this library?

No
