### ISSUE TITLE
Question: Spotify Region US 

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#163]
In your code I was able to find the "spotifyRegion" parameter with default for Europe = "2311". 

Is it possible to set the region to US = "3079"? How?

**Comment by hklages** [comment]
Having had a closer look at your code it does not seem to be possible to set the region. 

Suggestion: 

Add  additional optional parameter spotifyRegion to methods 
- AddUriToQueue
- SetAVTransportURI
and pass that parameter to GuessMetaDataAndTrackUri

**Comment by svrooij** [comment]
@hklages With the latest beta, you can set the environment variable `SONOS_REGION_SPOTIFY` as described [here](https://github.com/svrooij/node-sonos-ts/blob/beta/docs/getting-started.md)

**Comment by svrooij** [comment]
@hklages maybe the regions should be called differently. Like `Europe` and `Rest`

At least now they are configurable. The metadata helper is also public so you should be able to call it yourself.

I was thinking to maybe make a way to automatically send metadata and track uri to some server (opt-in) and then also try to resolve a track uri to metadata server side. That way we can start supporting way more music services without the need to manually export data like you proposed.

**Comment by hklages** [comment]
Region naming: Lets wait - maybe there is a region Asia or Arabia. And instead of "Rest" I prefer "Non-Europe". Rest sounds a bit unfriendly (personal point of view)

My recommendation is to add that song, album, playlist to My Sonos (favorites) and then launch it with from there by title instead of extracting the spotify number and build the metadata. My Sonos is so easy to and supports all music services, is always updated by Sonos, generates the metadata --- and I dont have to maintain it :-)
