### ISSUE TITLE
Feature request: Battery status

### ISSUE THREAD

**Issue by hubecker** [svrooij/node-sonos-ts#176]
## Battery status feature request

I like to get the battery status of my Sonos Move

With the following URL 

`http://<IP>:1400/status/batterystatus`

you get the battery status

the Browser shows the follwing:
<img width="336" alt="Bildschirm­foto 2023-02-15 um 23 20 26" src="https://user-images.githubusercontent.com/13958491/219195264-c3f74e60-36d3-4752-9575-aa50d793a683.png">

The HTTPBody of the request:

`<?xml version="1.0" ?><?xml-stylesheet type="text/xsl" href="/xml/review.xsl"?><ZPSupportInfo><LocalBatteryStatus><Data name="Health">UNKNOWN_batteryHealth</Data><Data name="Level">100</Data><Data name="Temperature">NORMAL</Data><Data name="PowerSource">SONOS_CHARGING_RING</Data></LocalBatteryStatus><!-- SDT: 0 ms --></ZPSupportInfo>`

**Comment by svrooij** [comment]
Thanks Hubert, I'll have a look next week.

**Comment by RlfSt** [comment]
The output for a Sonos Roam is the same:

```
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="/xml/review.xsl"?>
<ZPSupportInfo>
<LocalBatteryStatus>
<Data name="Health">GREEN</Data>
<Data name="Level">100</Data>
<Data name="Temperature">NORMAL</Data>
<Data name="PowerSource">SONOS_CHARGING_RING</Data>
</LocalBatteryStatus>
<!-- SDT: 0 ms -->
</ZPSupportInfo>
```

**Comment by hubecker** [comment]
Of course only when WLAN connected, not in bluetooth mode.

Don't know how to handle this one:
Would be also great to handle the mode meaning switching from WLAN to bluetooth and back.
But i don't know if there is an API, because even in the APP it is not possible.

**Comment by arndth** [comment]
Any updates for this request?

**Comment by svrooij** [comment]
Anyone who wants can create a pr for this, I don't own such a device so cannot test it myself.
