### ISSUE TITLE
Spotify playlist metadata

### ISSUE THREAD

**Issue by dialupdev** [svrooij/node-sonos-ts#177]
## Is your feature request related to a problem? Please describe

Hi there. Thanks for building this! It's a very cool project. I'm wondering if you've found a way to get metadata about the currently playing Spotify playlist, if any. I'm not seeing anything in the `Track` interface, or any other metadata location. Is this information simply not exposed by the Sonos API?

## Describe the solution you'd like

It'd be nice to see the playlist name in the track metadata.

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by svrooij** [comment]
Is the playlist started from the Sonos app or from the Spotify app? In the first case the data should be there in the enqueued metadata. Things started from Spotify are difficult.

**Comment by dialupdev** [comment]
Understood. Thanks for explaining. My use case is starting from Spotify. Sounds like this isn't possible, so I can close this for now.

**Comment by svrooij** [comment]
@celeryclub There should be some data still, but I think you have to query it or take it from the events.

Or maybe have a look at `EnqueuedTransportURIMetaData` in the [AVTransport event](https://sonos-ts.svrooij.io/sonos-device/services/av-transport-service.html#avtransportservice-event)

**Comment by dialupdev** [comment]
Thank you! I'll have a look and see if I can get anything going.
