### ISSUE TITLE
Request: Add GroupId to SonosDevice

### ISSUE THREAD

**Issue by orensharon** [svrooij/node-sonos-ts#182]
I would like to get the GroupId of each SonosDevice similary to the GroupName getter.
For example: 

    manager.Devices.forEach(d => {
      console.log('Device %s (%s) is joined in %s', d.Name, d.Uuid, d.GroupId)
      ....

Another solution that would work, is to add the groupId to the related group events data.

This would be helpful when dealing with Group Events:
     
    const onGroupRenderingChanged = async (data) => {
        const sonosDevice = manager.Devices.find(data.coordinatorId)
        const timestamp = Date.now()
        const deviceGroupId = sonosDevice.GroupId
        const eventGroupId = data.GroupId
        //const groupId = await sonosDevice.ZoneGroupTopologyService.GetZoneGroupAttributes()
        //        .then(attributes => attributes.CurrentZoneGroupID)
        const event = { groupId, data, timestamp }
        events.emit('group-rendering', event)
    }
    
    .....
    const id = sonosDevice.uuid
    sonosDevice.GroupRenderingControlService.Events.on(ServiceEvent, data => onGroupRenderingChanged({ id, data })
    ....
    ....

**Comment by svrooij** [comment]
Where do you need the group id for? Cannot oversee it at the moment.

**Comment by orensharon** [comment]
Hi,

I need the `GroupId` to identify the `Group` entity in the domain layer of my app.

When a `GroupZoneTopology` event is triggered, I analyze the changes within each group and emit a corresponding event to update the domain's state.

Similarly, a `GroupRenderingControl` event triggers another event with the `GroupId` and relevant data to modify the domain's state.

I'm considering using events like `Coordinator` to track group changes, but I'm still figuring out the best approach.

I'm open to exploring other solutions if you have any suggestions or alternatives.

Thanks.

**Comment by svrooij** [comment]
Have you checked the events on the manager?

Each player already received updates if the coordinator changes and sets the `.Coordinator` on the player.
