### ISSUE TITLE
Version 3.6.0 beta0007 decodes embedded XML

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#190]
### What happened

tsPlayer.ContentDirectoryService.Browse({
      'ObjectID': 'FV:2', 'BrowseFlag': 'BrowseDirectChildren', 'Filter': '*', 'StartingIndex': 0,
      'RequestedCount': REQUESTED_COUNT_MYSONOS, 'SortCriteria': ''
    })

provides now  a different output for property "Result" (it is decoded))
beta.7 "<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp
beta.5 "&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=

### What did you expect to happen
same output as beta 5

### How to reproduce it (minimal and precise)
Add some items to MySonos with the help of the SONOS APP and use the above command

### Environment

- sonos-ts version: beta-7
- OS: any
- node version (`node -v`): 20.11 (any)

**Comment by svrooij** [comment]
The change has to to with the change in the used xml library, please check out [this discussion](https://github.com/svrooij/node-sonos-ts/discussions/191) where I tried explaining the decision. I cannot go back on this.

For you no longer being able to read that data, this is exactly where [this code](https://github.com/svrooij/node-sonos-ts/blob/981226514c45a24a9d36213a6be0aa882ec3a874/src/services/content-directory.service.extension.ts#L18-L38) is for. It should parse the response from the **Browse** command, I modified the [XmlHelper](https://github.com/svrooij/node-sonos-ts/blob/981226514c45a24a9d36213a6be0aa882ec3a874/src/helpers/xml-helper.ts#L22-L24) to only decode if it is even encoded. So this code should work as expected.

```js
sonos.ContentDirectoryService.BrowseParsed({...});
```

**Comment by hklages** [comment]
... Next week I am going to work on it.
