### ISSUE TITLE
BUG: Subscription to (simple) Mute provides the false if muted. 

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#194]
### What happened

After having moved from 2.5.0 to 2.6.0-beta-10 the mute subscription provides wrong data:
(by the way beta-10 does not show up on the top instead beta-9 is on top of releases in Github) 
 
- RenderingControl service event does not provide the correct mute state instead it is always false.

### What did you expect to happen

Should be true if player changes from unmute to mute.

### How to reproduce it (minimal and precise)

1. Subcribe to RenderingControl service for a specific player (`.Events.on`)
2. change mute state to mute
output is always "false"

GroupRenderingControl works fine. 

### Debug logging

let me know what you need. Debugging is not so easy in Node-RED containers. 

### Environment

- sonos-ts version: 2.6.0-beta-10
- OS: unraid container, Windows11
- node version (`node -v`): any

**Comment by svrooij** [comment]
A fix will be there shortly. It was a small change that I overlooked with the xml parser

https://github.com/svrooij/node-sonos-ts/pull/195/files#diff-3ca06a54a05a61bac9a63c4703642d7c5e8669e3b58096bf0e277a347bb8fe7cR10

**Comment by svrooij** [comment]
@hklages version `2.6.0-beta.11` should fix your issue [npm](https://www.npmjs.com/package/@svrooij/sonos/v/2.6.0-beta.11), can you close this issue if your problem is solved?

**Comment by hklages** [comment]
Thanks! It works on my system and is also confirmed by another user.
