### ISSUE TITLE
PlayNotification support for Spotify Connect

### ISSUE THREAD

**Issue by Glurz** [svrooij/node-sonos-ts#199]
Hi

It's more of a question than a feature request. I'm experimenting with the PlayNotification method. If Sonos is playing music via Spotify Connect protocol, PlayNotification is unable to restore the state before the notification. I.e. it cannot resume the song that was playing before.
Is this due to the nature of the Spotify Connect protocol? I.e. if the connection between the controlling device and Sonos has been disconnected by the notification, it cannot be re-established by node-sonos-ts?

Thanks for some insights.

**Comment by svrooij** [comment]
That is exactly te reason.
You might have better luck using the `Playnotificationaudioclip` in the latest beta version.

It use the native notification support

**Comment by Glurz** [comment]
Thanks @svrooij, I‘ll try that.
