### ISSUE TITLE
Missing the "leave_group"

### ISSUE THREAD

**Issue by Rolf-M** [svrooij/node-sonos-ts#34]
Hi Sven,
as supposed by you, I had a look at your typescript version. Up to now I think it's cool, as the better group handling with the manager instance is something I was looking for. But I'm missing the "leave_group" function. I think I can make the speaker leaving the group using the "group_management" service, but it would be nice to have a leave function.
Could you add this?
Thanks Rolf

**Comment by svrooij** [comment]
Does this help?
https://svrooij.github.io/node-sonos-ts/classes/_services_av_transport_service_.avtransportservice.html#becomecoordinatorofstandalonegroup

'device.AVTransportService.BecomeCoordinatorOfStandaloneGroup()'
