### ISSUE TITLE
Events not working if using manager on multiple speakers

### ISSUE THREAD

**Issue by Rolf-M** [svrooij/node-sonos-ts#48]
Hi Sven,
I have an issue with events. I use manager to find the speakers (3 of them) and then I subscribe to the events of the speakers, through the speaker object given by the manager.
What happens, is that I get the track changes and AVTransport on one speaker, but all other events will not be fired any more. If I only use the events on one speaker everything is good.
I had a close behavior on the "old" api, where events where not fired if you did subscribe multiple time to a "global" event. But with your api I don't see any more difference in global and speaker events.
Regards, Rolf

**Comment by svrooij** [comment]
Hi Ralph,

Are your speakers grouped? Then some events won't fire on the child speakers. Also what version are you using of this library?

I'm using this on a pi using https://github.com/svrooij/sonos2mqtt and I can confirm it does emit all the events on all speakers.

Have you seen the [documentation on events](https://svrooij.github.io/node-sonos-ts/sonos-device/events.html)? In this new library you cannot get an instance of the SonosEventListener it's all managed for you.

So if you call `sonosDevice.Events.on(....)` it will automatically subscribe for those events. The events available are in the SonosEvents class `const SonosEvents = require('@svrooij/sonos').SonosEvents`

**Comment by Rolf-M** [comment]
Hi Stephan (sorry for mixing up your name!),

yes the speakers are grouped (partly), and I'm ungrouping and grouping them, this is why I need events, to get the grouping state.
What I was doing, you can see here : https://github.com/Rolf-M/node-red-contrib-sonos-test/blob/master/sonos-test-status.js but using this code, following your documentation, I will get the track Events on the master, but as soon as I subscribe multiple speakers, I will not get any AVTransport or volume information  or grouping on any speaker any more.

But then I saw a different code in your examples: https://github.com/svrooij/node-sonos-ts/blob/master/examples/use-manager.js There you use a different implementation to get some events. This will work in my scenario, but there I'm missing the volume for example. The is grouped or not I can calculate from the UUID, but the volume is essential...

So which way should I go? 

As you can see, I'm about to use your library to write some node-red implementation. I know there are a lot of sonos node-red variants now, but I think none of them is cool....

Regards, Rolf

**Comment by svrooij** [comment]
> sorry for mixing up your name
No problem, I hoped you would pick it up 😉 

I'm not sure what events you're looking for. If you use the [Manager](https://svrooij.github.io/node-sonos-ts/getting-started.html#use-sonos-manager) each device will manage the coordinator [automatically](https://github.com/svrooij/node-sonos-ts/blob/master/src/sonos-device.ts#L548-L581), this means you can call `Next()` on each speaker in the group and it will just work. And each speaker will emit the `coordinator` and `groupname` events.

You can checkout my other project that uses all events [here](https://github.com/svrooij/sonos2mqtt/blob/68f9742c605102fa00f2fd2471d5525875ad20b8/src/sonos-to-mqtt.ts#L98-L140)

It seems like you aren't using the manager at the moment. That shouldn't be a problem you can also listen for events on the `sonosDevice.ZoneGroupTopologyService` but them you'll have to manage all those features yourself.

I would go this way:

1. Use SonosManager to get the correct device and have it setup the groups correctly (not sure if you should keep a reference in Node Red)
2. Listen for events on the device like specified in the above sample.

**Comment by Rolf-M** [comment]
So, it seems that I've mixed up some coding examples.
I was using sonos manager, but subscribed the events directly to the speakers. If I subscribe the events like you do in your mqtt application, then it'll work.
Thank you for working out this library, it is a real improvement to the old sonos library.
Regards, Rolf

**Comment by svrooij** [comment]
No problem.
I hope this library will still work when Sonos will release their "new" stuff (when they kill functionality of the "old" speakers).
