### ISSUE TITLE
InitializeWithDiscovery never terminates

### ISSUE THREAD

**Issue by tjoskar** [svrooij/node-sonos-ts#50]
Hi,

I just found this lib and it looks really promising.

I don't know if this is a bug or if it is intended but if we take this script:
```ts
import { SonosManager } from '@svrooij/sonos';

const manager = new SonosManager();
manager.InitializeWithDiscovery(10).then(console.log);
```

and execute it, it will never terminate. It prints `true` and just hangs. Is that intended?

What I want to do is to get a device that I don't know the IP of (I do however know the name/uuid).

**Comment by svrooij** [comment]
The manager starts the event listener (to keep all the groups updated correctly).

For just doing discovery you could use the **SonosDeviceDiscovery** which is also exported.

If you check out this sample, you can see the intended use of the manager https://github.com/svrooij/node-sonos-ts/blob/master/examples/use-manager.js

**Comment by tjoskar** [comment]
Thanks for your response!

This gist seems to do the trick for me.

```ts
import { SonosDeviceDiscovery, SonosDevice } from '@svrooij/sonos';

async function run() {
  const deviceDiscovery = new SonosDeviceDiscovery();
  const player = await deviceDiscovery.SearchOne(10);

  const device = new SonosDevice(player.host, player.port);

  console.log(await device.AVTransportService.GetPositionInfo());
}

run();
```
