### ISSUE TITLE
Generated services from multiple devices

### ISSUE THREAD

**Issue by svrooij** [svrooij/node-sonos-ts#64]
Not all devices have the same services, I'm looking for a way to change the generator in a way that it will merge all the **discovered-services.json** from different models and turn it into a single library.

Any ideas?

See https://github.com/svrooij/sonos2mqtt/issues/104#issuecomment-643102066

https://github.com/svrooij/node-sonos-ts/compare/master...matthias-burgfried:master

**Comment by matthias-burgfried** [comment]
I have no idea, but if I can help you, just let me know. I could provide the services for Play:5 (G2), Beam, One (G1) and One Sl. Would the Sub (Generation 3) then also be interesting?
