### ISSUE TITLE
Use audioClip endpoint?

### ISSUE THREAD

**Issue by oscar-b** [svrooij/node-sonos-ts#67]
Wouldn't it make sense to use the `/audioClip` API for notifications? 

https://developer.sonos.com/code/making-sonos-talk-with-the-audioclip-api/

**Comment by svrooij** [comment]
At first glance they mention these libraries, which makes me think that you would still need to run something yourself.
> **google-tts-api**: This puts a nice, neat, promise-ready wrapper around the Google Text-to-Speech API.
> **simple-oauth2**: A handy package to simplify the process of getting and refreshing access tokens.
> **node-persist**: Mimics the HTML5 localStorage API used in browsers, so it’s pretty easily understood.

And the [Sonos developer](https://developer.sonos.com/) website, only talks about the cloud service to control your speakers.
While ok, it lakes most functionality that you're getting when controlling the speakers locally.

Using the (cloud) [audioClip](https://developer.sonos.com/reference/control-api/audioclip/) endpoint sounds nice, but are only supported in a V2 system (and I'm on the "I'm not updating and splitting my system"-camp).

**Comment by oscar-b** [comment]
> Using the (cloud) [audioClip](https://developer.sonos.com/reference/control-api/audioclip/) endpoint sounds nice, but are only supported in a V2 system (and I'm on the "I'm not updating and splitting my system"-camp).

Would you accept a PR adding this functionality to your library, as a separate endpoint?

**Comment by svrooij** [comment]
I'm willing to consider, but I'm kinda lost in how it should be working.

You probably need (might not be complete):

- Sonos Client ID and Secret (can these be saved in the source or should user generate himself)
- A Webserver (inside this library) to get the oauth flow callback
- Have the user authenticate
- Save the token
- Allow the user to call the endpoint

That said, it sounds like a nice improvement, I'm thinking you would be creating a new (as in extra) `PlayNotification` method? Like `PlayNotificationCloud`?

Apart from that, I'm wondering if they didn't make this endpoint locally on the S2 system, or if they made somewhat the same logic in the cloud.

**Comment by oscar-b** [comment]
Right, I didn't look that closely at all your code yet, I assumed you already had the auth handling done already. But if you're not using any cloud functionality yet that requires this I understand that you don't :/  

I haven't seen any information about providing this directly on the speakers, unfortunately. Not sure why they don't, it's a shame, but the functionality it provides seem far superior than the workarounds of saving speaker state and restoring so it might be worth it anyway.

One thing that doesn't seem possible yet with the `audioClip` endpoint is targeting groups of speakers, only individual (or paired I think).

There's also this project, based on the Sonos example: https://github.com/kevinvincent/hassio-addons/tree/master/sonos-audioclip-tts

**Comment by svrooij** [comment]
> I haven't seen any information about providing this directly on the speakers, unfortunately. Not sure why they don't, it's a shame, but the functionality it provides seem far superior than the workarounds of saving speaker state and restoring so it might be worth it anyway.

Have you seen the [PlayNotification](https://svrooij.io/node-sonos-ts/sonos-device/notifications-and-tts.html#notifications) method? There isn't any saving/restoring required. It's all handled by this library (and so far, with a delay of 700ms, I haven't had any problems with it.)

Sonos either implemented the same logic in the cloud, or they made a local endpoint on the speaker with the same logic. Somewhere the current song/playlist/volume has to be saved and restored afterwards.

If they made this endpoint on the local devices it would be great to check it out and see if it's better then the current solution.

**Comment by oscar-b** [comment]
> Have you seen the [PlayNotification](https://svrooij.io/node-sonos-ts/sonos-device/notifications-and-tts.html#notifications) method? There isn't any saving/restoring required. It's all handled by this library (and so far, with a delay of 700ms, I haven't had any problems with it.)

Yeah, looked like the same way Home Assistant does it, and it have issues with resuming streaming from for instance Spotify.


> Sonos either implemented the same logic in the cloud, or they made a local endpoint on the speaker with the same logic. Somewhere the current song/playlist/volume has to be saved and restored afterwards.

No, it ducks the playing audio and overlays the audioClip audio on top of it.

**Comment by svrooij** [comment]
How does your home assistant connect to sonos? Is it using this library or some other way (maybe [sonos2mqtt](https://github.com/svrooij/sonos2mqtt)?
I think by default home assistant uses an other library, that maybe didn't implement notifications correctly.
Or home assistant doesn't specify the mentioned **delay** of 700ms.

> No, it ducks the playing audio and overlays the audioClip audio on top of it.

This means they changed the speaker software (and maybe there is an endpoint for it).
Could you make a fork and run this command in the terminal (with an IP of a S2 speaker in it)?
```
cd src/generator/
SONOS_HOST=192.168.x.x node service-generator.js --save-description --load-files --generate
```

I'm really curious if it would change the discovered-services.json file.

**Comment by oscar-b** [comment]
> > No, it ducks the playing audio and overlays the audioClip audio on top of it.
> 
> This means they changed the speaker software (and maybe there is an endpoint for it).
> Could you make a fork and run this command in the terminal (with an IP of a S2 speaker in it)?
> 
> ```
> cd src/generator/
> SONOS_HOST=192.168.x.x node service-generator.js --save-description --load-files --generate
> ```
> 
> I'm really curious if it would change the discovered-services.json file.

No changes to `discovered-services.json` after running that, it only generated a new file: `discovered-services.gen2_S18.json`

**Comment by svrooij** [comment]
> No changes to discovered-services.json after running that, it only generated a new file: discovered-services.gen2_S18.json

Bummer.....

Your message still got me thinking. They made a [cloud api](https://developer.sonos.com/reference/control-api-list/) and they also made a new actually rest (no more soap 😄:tada:) api on the local device, but I never could get it to respond. So what about if I take a token from the cloud, and use that on the local api.

Care to investigate?

---
My guess

Remote URI: `https://api.ws.sonos.com/control/api/v1/players/{playerId}/audioclip`.

Local URI `http://sonosIp:1400/api/v1/audioclip`

---
I'm not against using the new api, but would rather not sacrifice all the control we have at the moment (local control and super fast notifications on the local network) over using the cloud for everything. But if we could use the cloud token to control the speakers over the local network that would be great. You can then also switch between then (eg. devices reachable = local control / device unreachable = cloud control).

**Comment by svrooij** [comment]
Local API endpoints:
<img width="481" alt="Screenshot 2020-08-13 at 10 52 30" src="https://user-images.githubusercontent.com/1292510/90115625-a137c700-dd54-11ea-809a-6c34a548441c.png">

Sadly no response (when tried with a cloud token):
<img width="913" alt="Screenshot 2020-08-13 at 11 01 51" src="https://user-images.githubusercontent.com/1292510/90115708-bd3b6880-dd54-11ea-9947-7934d56748b9.png">

I found you need to set
Header: `Authorization` value: `Bearer X-Sonos-Controller-ID:something`
or
Header: `Authorization` value: `X-Sonos-Controller-ID:something`

where I don't know what to put behind it.

**Comment by jnbht** [comment]
To give some new sparks on this topic. I have tested the audioClip feature with this node-plugin:
https://github.com/kevinvincent/hassio-addons/blob/master/sonos-audioclip-tts/

And it works on older speaker too (Play:3, Play:1, Playbar)
He uses the cloud API though. I do not know if it is possible to push the commands locally.

I keep looking. Would be so awesome!

**Comment by svrooij** [comment]
I’m all for this endpoint, but for now I’m delaying the S2 upgrade for as long as possible, because I have some old Play5 speakers that cannot be upgraded, so I will be left with a splitted system.
Anyone want to sponsor me a test speaker, so I can test this out. Creating this is probably easy. Also thinking about running some server to handle the redirect part

**Comment by jnbht** [comment]
Ah, the got old Play:5. Loved it!
Allright. I get that you won't switch with this speaker ;)

**Comment by hklages** [comment]
SONOS documentation at [developer page](https://developer.sonos.com/build/connected-home-get-started/architecture/)

> The Control API on the LAN is not available for wide release. We’ll add a blog post when it is available.
> Use the Control API on the cloud to communicate with a Sonos player. The Sonos cloud manages ...

**Comment by thoelzl** [comment]
The Control API is also available on local networks via a websocket connection to the speaker. See my comment on this issue:
[https://github.com/bencevans/node-sonos/issues/530](https://github.com/bencevans/node-sonos/issues/530)

**Comment by svrooij** [comment]
@thoelzl interesting find!! I always put this of because of the need for a cloud connection.
In the mean time we switched to a splitted system so I should be able to test it.

Few questions though:

- what happens when you send the command to Player A with the id of player B?
- does it support groups?
- what happens when you send multiple commands in rapid succession?

**Comment by thoelzl** [comment]
I have tested the use case of your first question. Send command to Player A with the id of player B does not work. You need a dedicated connection with the device for the audioclip command to work.

Groups should be supported but not with the audioclip command. This command is currently only supported on player level, not groups.

I have only tested a few simple commands, so i can't comment on your last question.

**Comment by svrooij** [comment]
@thoelzl 👀👇

![image](https://user-images.githubusercontent.com/1292510/219019888-7637d753-5575-4c3f-bd07-6fa4ff48f2ac.png)

**Comment by thoelzl** [comment]
Great, thanks for the fast solution!

**Comment by svrooij** [comment]
@thoelzl could you let me know what you think? Does it work for you? If you also use sonos2mqtt, you can also switch to use the new endpoint. https://github.com/svrooij/sonos2mqtt/discussions/191

**Comment by hklages** [comment]
... that's a really cool feature - love it!

**Comment by svrooij** [comment]
@hklages does it work for you? What is your first experience?

**Comment by hklages** [comment]
The first tests were excellent. Even in a group the specified player played
the clip. Tomorrow I will do more tests. What happens when I omit the
volume? Do you set a default volume or is the current player volume used?

**Comment by svrooij** [comment]
It will either use the players volume if that is pre-loaded (when using the events) or `25`.

All the way at the end in this line.

https://github.com/svrooij/node-sonos-ts/blob/0eb55f498178a3ef717077b5526d4f9d45e4f5a5/src/sonos-device.ts#L664

**Comment by hklages** [comment]
Did some more testing on Beam, Roam, Play:5, Play:3, Play:1. The audio clip works fine on all players with both http locally and https internet. If the players are grouped, all are going quite and the selected player plays the notification. To have them all playing the notification I can send to all players.  

The "onlyWhenPlaying=true" does not work  - maybe because I don't use your event manager. 

I use PlayNotificationAudioClip:

```
await selectedPlayer.PlayNotificationAudioClip({
      trackUri: validatedUri,
      onlyWhenPlaying: validatedOnlyWhenPlaying, 
      volume: validatedVolume
    })
```

**Comment by hklages** [comment]
... looking at the code an api key is needed and I assume it is yours. Right?

**Comment by svrooij** [comment]
> ... looking at the code an api key is needed and I assume it is yours. Right? 

No comment.....









👇
https://github.com/bencevans/node-sonos/issues/530#issuecomment-1430039043

**Comment by svrooij** [comment]
![image](https://github.com/svrooij/node-sonos-ts/assets/1292510/2b81dc40-c4d6-439f-9eea-8adde2b72887)
