### ISSUE TITLE
Mute works only once 

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#79]
```
playerKueche.Events.on(SonosEvents.Mute, value => {
      node.send({ payload: value, topic: 'Mute' })
 })

playerKueche.Events.on(SonosEvents.Volume, value => {
    node.send({ payload: value, topic: 'Volume' })
})
```

Volume works fine, mute only once.

**Comment by svrooij** [comment]
I've verified this as a bug, have to investigate some more.

**Comment by hklages** [comment]
Thanks - you are lightning fast. 

In this phase I don't want to install betas - can wait for official release. 

When will 2.2.0 be released?

**Comment by svrooij** [comment]
I was waiting for other issues that might pop-up, fixing those in the beta and then make one big release.

> In this phase I don't want to install betas - can wait for official release.

You should try it, since it has support for external music services. Like browsing Spotify is now possible.

**Comment by hklages** [comment]
What about GroupMute? Is that also fixed? In current version it is always "false".

**Comment by svrooij** [comment]
Did I build a GroupMute Event? 😲 Or do you mean the https://svrooij.io/sonos-api-docs/services/group-rendering-control.html#event-variables ?

**Comment by hklages** [comment]
```
playerKueche.GroupRenderingControlService.Events.on(ServiceEvents.Data, data => {
      node.send({ payload: data, topic: 'GroupRendering' })
})
```

**Comment by svrooij** [comment]
https://github.com/svrooij/node-sonos-ts/releases/tag/v2.2.0-beta.4
