### ISSUE TITLE
How to unsubscribe?

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#85]
Hi - me again :-) I just installed 2.2.0. 

How to unsubscribe? 

This code  (the volume is only to demonstrate, that player is defined)
```
console.log('volume >>' + await player.Volume)
const x = await player.cancelAllSubscriptions()
```

produces: 

```
volume >>14
(node:49824) UnhandledPromiseRejectionWarning: TypeError: player.cancelAllSubscriptions is not a function
    at cancelAll (C:\Users\hekla\Development\node-red-contrib-sonos-events\src\sonosevents-notify.js:122:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:49824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by svrooij** [comment]
You can call `device.CancelEvents()` on the device. https://github.com/svrooij/node-sonos-ts/blob/eeb96398689ae79972f7a3717e446a7453022f78/src/sonos-device.ts#L524

But the easiest way is to just remove your listener from the event emitter.

Check-out the sample [here](https://github.com/svrooij/node-sonos-ts/blob/master/examples/events.js)

[here](https://github.com/svrooij/node-sonos-ts/blob/eeb96398689ae79972f7a3717e446a7453022f78/src/services/base-service.ts#L316) is the code that triggers the unsubscribe if you remove the last listener.

**Comment by hklages** [comment]
Hi. I did some debugging.

To subscribe: works fine: 
code: `player.ZoneGroupTopologyService.Events.on(ServiceEvents.Data, data => { ... })`

to unsubscribe: does not work
code: 
```
const x = await player.ZoneGroupTopologyService.Events.removeAllListeners(ServiceEvents.Data)
console.log('subscription canceled' + JSON.stringify(x))
```
Result: subscription canceled{"_events":{},"_eventsCount":2} - so the method was executed. 

But when looking at the modified /status I get:
my code modification to see all subscribtions: ` subscrptionCount: Object.keys(this.subscriptions),`

Result: 
`{"host":"192.168.178.61","port":6329,"subscriptionUrl":"http://192.168.178.61:6329/sonos/{sonos-uuid}/{serviceName}","listeningSince":"2020-12-19T07:30:15.782Z","subscrptionCount":["uuid:RINCON_949F3EC13B9901400_sub0000004382","uuid:RINCON_949F3EC13B9901400_sub0000004383"]}`

So it seems that
- for every new call (even the same player, same service) a new subscription is created
- the old ones are not removed

**Comment by svrooij** [comment]
If you remove all listeners from the .Events it does unsubscribe from the service. That is why you see that if you re-subscribe a new subscription is created.

I never bothered to remove the old subscription link from the SonosEventListener (the array that is counted with the status endpoint) because the array was only used to deliver the events to the right service. And since the old subscriptions where removed from the speakers no new events would be delivered on that service.

**Comment by hklages** [comment]
OK. Understand. I close this issue. 

I suggest to replace the last line by 
`subscriptionHistory: Object.keys(this.subscriptions)`

or subscriptionHistoryLength. 

Summary: 
- "Event listener" is being started with the first subscription (if not already started with Groupmanager)
-  Subscribing and ".Events.removeAllListeners" seems to work fine (doing tests over the next 2 weeks)
- "Event listener" stays alive even if all listeners are removed
- status can be checked with "http://127.0.0.1:6329/status"  (returns "can't reach this page" if stopped)
