### ISSUE TITLE
AlbumArtUri is sometimes wrong encoded

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#93]
Album Art URI does not work  - prime playlist, 4. Winter-Hits, Miley Cyrus Prisoner
[sonos-ts](http://192.168.178.37:1400/getaa?s=1&u=x-sonosapi-hls-static:catalog%2ftracks%2fB08LP1K9M3%2f%3fplaylistAsin%3dB08R3YYJG1%26playlistType%3dprimePlaylist%3fsid%3d201%26flags%3d0%26sn%3d19)

`http://192.168.178.37:1400/getaa?s=1&u=x-sonosapi-hls-static:catalog%2ftracks%2fB08LP1K9M3%2f%3fplaylistAsin%3dB08R3YYJG1%26playlistType%3dprimePlaylist%3fsid%3d201%26flags%3d0%26sn%3d19`

With node-sonos JavaSript the result is the following and that works:  
[node-sonos](http://192.168.178.37:1400/getaa?s=1&u=x-sonosapi-hls-static%3acatalog%252ftracks%252fB08LP1K9M3%252f%253fplaylistAsin%253dB08R3YYJG1%2526playlistType%253dprimePlaylist%3fsid%3d201%26flags%3d0%26sn%3d19)

`http://192.168.178.37:1400/getaa?s=1&u=x-sonosapi-hls-static%3acatalog%252ftracks%252fB08LP1K9M3%252f%253fplaylistAsin%253dB08R3YYJG1%2526playlistType%253dprimePlaylist%3fsid%3d201%26flags%3d0%26sn%3d19`

**Comment by svrooij** [comment]
This seems strange.... I don't know why, but the code explicitly replaces `%25` with `%` and `%3a` with `: `. 

I've tested with spotify, and they both seem to work:
- `/getaa?s=1&u=x-sonos-spotify:spotify:track:7FNsGGAGyMoSwjH3ivmcep%3fsid%3d9%26flags%3d8224%26sn%3d7` (current result, with `%3a` replaced).
- `/getaa?s=1&u=x-sonos-spotify%3aspotify%3atrack%3a7FNsGGAGyMoSwjH3ivmcep%3fsid%3d9%26flags%3d8224%26sn%3d7` (without replacement)

So I would opt to remove the replacement, but to put a comment to this issue in the code. What do you think @hklages ?

**Comment by svrooij** [comment]
This is fixed in the latest beta right?

**Comment by svrooij** [comment]
@hklages can you check this issue is fixed in the latest versions?

**Comment by hklages** [comment]
great - it works now @2.3.0
